name: Create Release

on:
  push:
    tags:
      - 'v*'          # Only trigger on version tags like v1.0.0, v2.1.3
      - '[0-9]*'      # Or tags starting with numbers like 1.0.0, 2.1.3
  workflow_dispatch:  # Enables manual trigger

jobs:
  release:
    name: Create Gitea Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up variables
        id: vars
        run: |
          # Use GITHUB_REF_NAME (short ref) if available, otherwise parse GITHUB_REF
          if [ -n "$GITHUB_REF_NAME" ]; then
            TAG_NAME="$GITHUB_REF_NAME"
          else
            TAG_NAME="${GITHUB_REF##*/}"
          fi
          
          echo "Detected tag: $TAG_NAME"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Create ZIP archive
        run: |
          # Create zip with full path for HACS (content_in_root: false)
          # HACS expects: /manifest.json
          cd custom_components/dynamic_ocpp_evse         
          zip -r dynamic-ocpp-evse.zip .

      - name: Create Gitea Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Dynamic OCPP EVSE ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: custom_components/dynamic_ocpp_evse/dynamic-ocpp-evse.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITEA_TOKEN }}
