name: Auto Pre-Release (dev / pre-release)

on:
  push:
    branches:
      - dev
      - pre-release

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine tag name
        run: |
          # Use GITHUB_REF_NAME (short ref) if available, otherwise parse GITHUB_REF
          if [ -n "$GITHUB_REF_NAME" ]; then
            BRANCH="$GITHUB_REF_NAME"
          else
            BRANCH="${GITHUB_REF##*/}"
          fi
          
          echo "Detected branch: $BRANCH"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          
          TIMESTAMP=$(date -u +"%Y%m%d-%H%M%S")

          if [ "$BRANCH" = "dev" ]; then
            TAG_NAME="dev-${TIMESTAMP}"
          elif [ "$BRANCH" = "pre-release" ]; then
            VERSION=$(jq -r '.version' custom_components/dynamic_ocpp_evse/manifest.json)
            TAG_NAME="${VERSION}-pre-${TIMESTAMP}"
          else
            echo "Unsupported branch: $BRANCH"
            exit 1
          fi

          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Create ZIP archive
        run: |
          # Create zip with full path for HACS (content_in_root: false)
          # HACS expects: /manifest.json
          cd custom_components/dynamic_ocpp_evse         
          zip -r dynamic-ocpp-evse.zip .

      - name: Create Gitea pre-release
        run: |
          # Create the tag first
          git config user.name "Gitea Actions"
          git config user.email "actions@gitea.local"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"
          
          # Create the release using Gitea API
          RELEASE_RESPONSE=$(curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITEA_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"tag_name\": \"$TAG_NAME\", \"name\": \"Dynamic OCPP EVSE $TAG_NAME\", \"prerelease\": true, \"draft\": false}" \
            "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/releases")
          
          echo "Release response: $RELEASE_RESPONSE"
          RELEASE_ID=$(echo "$RELEASE_RESPONSE" | jq -r '.id')
          echo "Release ID: $RELEASE_ID"
          
          # Upload the asset
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITEA_TOKEN }}" \
            -H "Content-Type: application/zip" \
            --data-binary @custom_components/dynamic_ocpp_evse/dynamic-ocpp-evse.zip \
            "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=dynamic-ocpp-evse.zip"
