name: Auto Pre-Release (dev / pre-release)

on:
  push:
    branches:
      - dev
      - pre-release

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      - name: Run test suite
        run: |
          python dev/tests/run_tests.py dev/tests/scenarios

      - name: Determine tag name
        run: |
          # Use GITHUB_REF_NAME (short ref) if available, otherwise parse GITHUB_REF
          if [ -n "$GITHUB_REF_NAME" ]; then
            BRANCH="$GITHUB_REF_NAME"
          else
            BRANCH="${GITHUB_REF##*/}"
          fi

          echo "Detected branch: $BRANCH"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"

          VERSION=$(jq -r '.version' custom_components/dynamic_ocpp_evse/manifest.json)
          TIMESTAMP=$(date -u +"%Y%m%d.%H%M")

          if [ "$BRANCH" = "dev" ]; then
            TAG_NAME="${VERSION}-dev.${TIMESTAMP}"
          elif [ "$BRANCH" = "pre-release" ]; then
            TAG_NAME="${VERSION}-rc.${TIMESTAMP}"
          else
            echo "Unsupported branch: $BRANCH"
            exit 1
          fi

          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create ZIP archive
        run: |
          # Create zip with full path for HACS (content_in_root: false)
          # HACS expects: /manifest.json
          cd custom_components/dynamic_ocpp_evse         
          zip -r dynamic-ocpp-evse.zip .

      - name: Delete previous dev releases (dev branch only)
        if: env.BRANCH == 'dev'
        run: |
          echo "Cleaning up previous dev releases..."
          # Match both old format (dev-*) and new format (*-dev.*)
          DEV_PATTERN='(^dev-|.*-dev\\.)'

          # Delete previous dev releases from Gitea
          echo "Fetching Gitea releases..."
          GITEA_RELEASES=$(curl -s \
            -H "Authorization: token ${{ secrets.GITEA_TOKEN }}" \
            "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/releases")

          echo "$GITEA_RELEASES" | jq -r '.[] | select(.tag_name | test("'"$DEV_PATTERN"'")) | "\(.id) \(.tag_name)"' | while read -r RELEASE_ID RELEASE_TAG; do
            if [ -n "$RELEASE_ID" ] && [ "$RELEASE_ID" != "null" ]; then
              echo "Deleting Gitea release: $RELEASE_TAG (ID: $RELEASE_ID)"
              curl -s -X DELETE \
                -H "Authorization: token ${{ secrets.GITEA_TOKEN }}" \
                "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/releases/$RELEASE_ID"

              echo "Deleting Gitea tag: $RELEASE_TAG"
              curl -s -X DELETE \
                -H "Authorization: token ${{ secrets.GITEA_TOKEN }}" \
                "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/tags/$RELEASE_TAG"
            fi
          done

          # Delete previous dev releases from GitHub
          echo "Fetching GitHub releases..."
          GH_RELEASES=$(curl -s \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/LeoAlioth/Dynamic_OCPP_EVSE/releases")

          echo "$GH_RELEASES" | jq -r '.[] | select(.tag_name | test("'"$DEV_PATTERN"'")) | "\(.id) \(.tag_name)"' | while read -r RELEASE_ID RELEASE_TAG; do
            if [ -n "$RELEASE_ID" ] && [ "$RELEASE_ID" != "null" ]; then
              echo "Deleting GitHub release: $RELEASE_TAG (ID: $RELEASE_ID)"
              curl -s -X DELETE \
                -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com/repos/LeoAlioth/Dynamic_OCPP_EVSE/releases/$RELEASE_ID"

              echo "Deleting GitHub tag: $RELEASE_TAG"
              curl -s -X DELETE \
                -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com/repos/LeoAlioth/Dynamic_OCPP_EVSE/git/refs/tags/$RELEASE_TAG"
            fi
          done

          echo "Cleanup complete!"

      - name: Delete previous pre-release releases (same version, pre-release branch only)
        if: env.BRANCH == 'pre-release'
        run: |
          # Safety: abort if VERSION is empty to avoid deleting all releases
          if [ -z "$VERSION" ]; then
            echo "ERROR: VERSION is empty — aborting cleanup to prevent deleting all releases"
            exit 1
          fi

          # Match both old format (VERSION-pre-*) and new format (VERSION-rc.*)
          RC_PATTERN="${VERSION}"'-(pre-|rc\\.)'
          echo "Cleaning up pre-release releases matching: ${RC_PATTERN}"

          # Delete previous pre-releases with same version from Gitea
          echo "Fetching Gitea releases..."
          GITEA_RELEASES=$(curl -s \
            -H "Authorization: token ${{ secrets.GITEA_TOKEN }}" \
            "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/releases")

          echo "$GITEA_RELEASES" | jq -r '.[] | select(.tag_name | test("'"$RC_PATTERN"'")) | "\(.id) \(.tag_name)"' | while read -r RELEASE_ID RELEASE_TAG; do
            if [ -n "$RELEASE_ID" ] && [ "$RELEASE_ID" != "null" ]; then
              echo "Deleting Gitea release: $RELEASE_TAG (ID: $RELEASE_ID)"
              curl -s -X DELETE \
                -H "Authorization: token ${{ secrets.GITEA_TOKEN }}" \
                "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/releases/$RELEASE_ID"

              echo "Deleting Gitea tag: $RELEASE_TAG"
              curl -s -X DELETE \
                -H "Authorization: token ${{ secrets.GITEA_TOKEN }}" \
                "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/tags/$RELEASE_TAG"
            fi
          done

          # Delete previous pre-releases with same version from GitHub
          echo "Fetching GitHub releases..."
          GH_RELEASES=$(curl -s \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/LeoAlioth/Dynamic_OCPP_EVSE/releases")

          echo "$GH_RELEASES" | jq -r '.[] | select(.tag_name | test("'"$RC_PATTERN"'")) | "\(.id) \(.tag_name)"' | while read -r RELEASE_ID RELEASE_TAG; do
            if [ -n "$RELEASE_ID" ] && [ "$RELEASE_ID" != "null" ]; then
              echo "Deleting GitHub release: $RELEASE_TAG (ID: $RELEASE_ID)"
              curl -s -X DELETE \
                -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com/repos/LeoAlioth/Dynamic_OCPP_EVSE/releases/$RELEASE_ID"

              echo "Deleting GitHub tag: $RELEASE_TAG"
              curl -s -X DELETE \
                -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com/repos/LeoAlioth/Dynamic_OCPP_EVSE/git/refs/tags/$RELEASE_TAG"
            fi
          done

          echo "Cleanup complete!"

      - name: Create Gitea pre-release
        run: |
          # Create the tag first
          git config user.name "Gitea Actions"
          git config user.email "actions@gitea.local"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"
          
          # Create the release using Gitea API
          RELEASE_RESPONSE=$(curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITEA_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"tag_name\": \"$TAG_NAME\", \"name\": \"Dynamic OCPP EVSE $TAG_NAME\", \"prerelease\": true, \"draft\": false}" \
            "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/releases")
          
          echo "Gitea Release response: $RELEASE_RESPONSE"
          RELEASE_ID=$(echo "$RELEASE_RESPONSE" | jq -r '.id')
          echo "Gitea Release ID: $RELEASE_ID"
          
          # Upload the asset to Gitea
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITEA_TOKEN }}" \
            -H "Content-Type: application/zip" \
            --data-binary @custom_components/dynamic_ocpp_evse/dynamic-ocpp-evse.zip \
            "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=dynamic-ocpp-evse.zip"
          
          echo "Gitea pre-release created successfully!"

      - name: Create GitHub pre-release
        run: |
          echo "Creating GitHub pre-release for tag: $TAG_NAME"
          
          # Wait a moment for the tag to sync to GitHub mirror
          sleep 5
          
          # Create the release using GitHub API
          RELEASE_RESPONSE=$(curl -s -X POST \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "{\"tag_name\": \"$TAG_NAME\", \"name\": \"Dynamic OCPP EVSE $TAG_NAME\", \"prerelease\": true, \"draft\": false}" \
            "https://api.github.com/repos/LeoAlioth/Dynamic_OCPP_EVSE/releases")
          
          echo "GitHub Release response: $RELEASE_RESPONSE"
          RELEASE_ID=$(echo "$RELEASE_RESPONSE" | jq -r '.id')
          echo "GitHub Release ID: $RELEASE_ID"
          
          if [ "$RELEASE_ID" = "null" ] || [ -z "$RELEASE_ID" ]; then
            echo "Failed to create GitHub release"
            exit 1
          fi
          
          # Upload the asset to GitHub
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/zip" \
            --data-binary @custom_components/dynamic_ocpp_evse/dynamic-ocpp-evse.zip \
            "https://uploads.github.com/repos/LeoAlioth/Dynamic_OCPP_EVSE/releases/$RELEASE_ID/assets?name=dynamic-ocpp-evse.zip"
          
          echo "GitHub pre-release created successfully!"
